name: "Neolink-latest"
description: "Will run latest Neolink directly as App in HAOS"
version: "0.8.3-rc.3"
slug: "neolink-latest"
url: "https://github.com/pacorreia/hassio-addons"
image: "docker.io/pfmc82/neolink"
arch:
  - amd64
  - aarch64
host_network: true
map:
  - type: addon_config
    read_only: False
  - type: homeassistant_config
    read_only: False
options:
  mode: rtsp
  log: info
ulimits:
  nofile:
    soft: 65536
    hard: 65536
schema:
  mode: list(rtsp|mqtt|dual)
  log: list(info|warn|error|debug)
